### PR TITLE
Add command mc!info for in-server use by all

### PR DESCRIPTION
**Pull request by kevinlul**
## Description

This is a comprehensive way to access details like the Challonge link, participant limit, number of registrations, registered byes, and who's in charge. It's allowed for everybody because the id has to be known in the first place. Cannot be used in direct messages to figure out all tournaments. Will not ping any mentioned user. `createTournamentEmbed` is a reusable pure function for the future.

## Checklist

- [x] I am following the [contributing guidelines](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/.github/CONTRIBUTING.md).
- [x] I have updated any relevant [user guides](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/guides).
- [x] I have updated any relevant [documentation](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/docs).
- [x] I have updated the [changelog](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/changelog.md), or this change is not user-facing.

### CODE REVIEW

**Comment by kevinlul** [comment]
We might be able to use something like this for a more responsive registration message with more details.

**Review by AlphaKretin — APPROVED** [review]
This rocks! Depending on how today goes I might throw together some tests for it

**Comment by kevinlul** [comment]
I could refactor for a more reusable and testable `createTournamentEmbed` function.

**Comment by AlphaKretin** [comment]
That could certainly be useful but wouldn't necessarily change testing a ton, it just simplifies testing command input/output into function input/output.

**Review by AlphaKretin — APPROVED** [review]

**Comment by kevinlul** [comment]
Merged from mobile 📱,  hope it works well.

**Pull request merged**
