### PR TITLE
Escape markdown characters from discord usernames

### PR DESCRIPTION
**Pull request by AlphaKretin**
## Description

This option is on by default but has a parameter to disable it for when usernames are printed to non-discord sources.

## Checklist

- [x] I am following the [contributing guidelines](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/.github/CONTRIBUTING.md).
- [x] I have updated any relevant [user guides](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/guides).
- [x] I have updated any relevant [documentation](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/docs).
- [x] I have updated the [changelog](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/changelog.md), or this change is not user-facing.

### CODE REVIEW

**Comment by AlphaKretin** [comment]
Two things of note: `csv.ts` in #303 will need to be updated for this after both are merged, and when starting a round the same call to `getRESTUsername` is used for both Discord printing and logging, this is probably best resolved by publicly exposing the escape function but I'm leaving that for discussion.

**Review by kevinlul — COMMENTED** [review]
I think this would make more sense if it was opt-in and the places that need to escape do it explicitly. The escape function can be common. I think it might be missing the tilde?

**Comment by kevinlul** [comment]
So we are escaping the backslash, asterisk, underscore, backtick, right angle bracket, and tilde?

**Comment by AlphaKretin** [comment]
Oh, I'm not sure what the right angle bracket is doing there. The intent is to escape escapes (backslash), bold, italics (asterisk), underline (underscore), code blocks (backtick) and strikethrough (tildes). I can't think of any other markdown features discord supports that would occur in usernames.

**Comment by AlphaKretin** [comment]
Rebased onto master after merging #303, `csv.ts` does not in fact need updating since `escape=false` is the default.

**Review by kevinlul — APPROVED** [review]
angle brackets and colons not technically required https://discord.com/developers/docs/resources/user

**Pull request merged**
