### PR TITLE
CLI: add leave server

### PR DESCRIPTION
**Pull request by kevinlul**
## Description

Unclear how to organize CLIs at the moment. This can be invoked post-transpilation or through ts-node.

## Checklist

- [x] I am following the [contributing guidelines](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/.github/CONTRIBUTING.md).
- [x] I have updated any relevant [user guides](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/guides).
- [x] I have updated any relevant [documentation](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/docs).
- [x] I have updated the [changelog](https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/changelog.md), or this change is not user-facing.

### CODE REVIEW

**Comment by AlphaKretin** [comment]
`cli` is a good name for the folder, but if we're instantiating it, I think we should move `clean.ts` there from `util`. it would also be nice to have one npm script as a shortcut to the ts-node binary if possible, rather than making a separate command for each one (you haven't here, it's what I've done with `clean`).

**Comment by AlphaKretin** [comment]
Documentation for cli commands can perhaps be a new seperate file linked to in the developer section of the readme.

**Review by AlphaKretin — APPROVED** [review]
it might be good to clean up `delete.ts` with arg checking like `leave.ts` has but that's OOS. I've gone ahead and checked the other checkboxes, you've written documentation and I feel this doesn't belong in the changelog. The README does need to point to `usage-cli.md` but maybe you intend to do that once it's merged?

**Comment by kevinlul** [comment]
I don't think the link is necessary for now.

**Comment by AlphaKretin** [comment]
i can see the argument for that, but it's not really any less necessary than the other details on how to run a fork of the bot. either way it doesn't matter hugely atm so if you strongly feel it's unnecessary go ahead and merge

**Pull request merged**
