### PR TITLE
Add guides for host commands

### PR DESCRIPTION
**Pull request by AlphaKretin**
## Description

Adds guides on how to use commands for tournament hosts, specialised to include the tournaments ID. The guides are not as comprehensive as the player guide, as we assume hosts know roughly what they're doing, or at least can ask us. Guides are separated into several sections for relevance and character limits.
- [x] `create`-`open`
- [x] `open`-`start`
- [x] `start`-`finish`
- [x] More new lines, block text, or some other way to improve the presentation of the guide messages.
- [x] Load guide text from template files.

## Checklist

- [x] I am following the [contributing guidelines]( https://github.com/AlphaKretin/emcee-tournament-bot/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AlphaKretin** [comment]
I haven't added a test for the guide to the "Start Tournament" tests because that appears to be in the middle of a transition from the current system to being properly mocked.

**Review by kevinlul — APPROVED** [review]
🚀

**Comment by AlphaKretin** [comment]
Reverted to draft due to an agreement that we need a few more improvements. 
- More new lines, block text, or some other way to improve the presentation of the guide messages.
- Load guide text from template files.

**Comment by AlphaKretin** [comment]
I'm not entirely sure how the guide files are going to interact with `bot` in Docker, hopefully @kevinlul can answer that.

**Review by kevinlul — APPROVED** [review]
Overall this is great, and provides an easy step to have guide formatting be its own module for easier testing.

**Pull request merged**
